# vLLM EC2 Image Configuration
# This file contains all configuration for building, testing, and releasing the vLLM EC2 image

# Image identification

image:
  name: "vllm-ec2"
  description: "vLLM for EC2 instances"


# env:
#   # Common
#   CONTAINER_TYPE: "general"
#   FRAMEWORK: "vllm"
#   PYTHON_VERSION: "py312"
#   CUDA_VERSION: "cu129"
#   OS_VERSION: "ubuntu22.04"

#   # vLLM EC2
#   VLLM_VERSION: 0.13.0
#   PROD_EC2_IMAGE: vllm:0.13-gpu-py312-ec2

#   # vLLM SageMaker
#   PROD_SAGEMAKER_IMAGE: vllm:0.13-gpu-py312

#   # vLLM RayServe
#   VLLM_RAYSERVE_VERSION: 0.10.2
#   PROD_RAYSERVE_IMAGE: vllm:0.10-gpu-py312-rayserve

#   # CI environment configuration
#   FORCE_COLOR: "1"

# Build configuration
common:
  framework: "vllm"
  framework_version: "0.14.0" # original VLLM_VERSION
  job_type: "general" # original CONTAINER_TYPE
  python_version: "py312"
  cuda_version: "cu129"
  os_version: "ubuntu22.04"
  customer_type: "ec2"
  arch_type: "x86"
  prod_image: "vllm:0.14-gpu-py312-ec2" # original PROD_EC2_IMAGE PROD_SAGEMAKER_IMAGE PROD_RAYSERVE_IMAGE
  device_type: "gpu"

# Release configuration
release:
  release: true
  force_release: false
  public_registry: true
  private_registry: true
  enable_soci: false
  source_stage: private
  target_stage: gamma


