name: Runner Cleanup

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: pr-cleanup-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test-bld-0:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-bld-1:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-bld-2:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-bld-3:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-def-0:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-def-1:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-def-2:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-def-3:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:default-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-0:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-1:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-2:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-3:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-4:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-5:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-6:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-7:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6-8:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6e-0:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6exl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup

  test-g6e-1:
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6exl-runner
    steps:
      - uses: actions/checkout@v5
      - name: Disk Cleanup
        uses: ./.github/actions/tmp-cleanup
