name: Publish Documentations via GitHub Pages

on:
  push:
    branches: [doc-poc]
    paths:
      - "**docs**"
  workflow_dispatch:

concurrency:
  group: publish-docs-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true

      - name: Checkout tutorials repository
        uses: actions/checkout@v5
        with:
          repository: aws-samples/sample-aws-deep-learning-containers
          ref: main
          path: docs/tutorials

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
