name: Publish Documentations via GitHub Pages

on:
  push:
    branches: [doc-poc]
    paths:
      - "docs/**"
      - "mkdocs.yaml"
      - "requirements/docs.txt"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

concurrency:
  group: publish-docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base branch (safe)
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          fetch-depth: 0
          submodules: true

      - name: Install dependencies
        run: pip install -r requirements/docs.txt

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
