name: Example Workflow

on:
  workflow_run:
    workflows: ["PR Permission Gate"]
    types:
      - completed

permissions:
  contents: read

jobs:  
  pre-commit:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  
  example-on-default-runner:
    needs: [pre-commit]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
  
  example-on-build-runner:
    needs: [example-on-default-runner]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
      - run: .github/scripts/buildkitd.sh

  example-on-g6xl-runner-1:
    needs: [example-on-build-runner]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
      - run: |
          nvidia-smi
  
  example-on-g6xl-runner-2:
    needs: [example-on-build-runner]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
      - run: |
          nvidia-smi
