name: Example Workflow

on:
  pull_request:
    branches: 
      - main

permissions:
  contents: read

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:  
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files
  
  example-on-default-runner:
    needs: [pre-commit]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
  
  example-on-build-runner:
    needs: [example-on-default-runner]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-build-runner
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
      - run: .github/scripts/buildkitd.sh
      - name: build vllm-rayserve-ec2 image
        shell: bash
        run: |
          DATE=$(date +"%Y-%m-%d")
          COMMIT_REF=$(git rev-parse HEAD)
          REPO=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/ci
          TAG=vllm-0.10.2-gpu-py312-cu128-ubuntu22.04-rayserve-ec2-pr-${{ github.event.pull_request.number }}-"${COMMIT_REF}"
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          DOCKER_BUILDKIT=1 docker build --progress plain \
            --build-arg CACHE_REFRESH="${DATE}" \
            --tag "${REPO}":"${TAG}" \
            --target vllm-rayserve-ec2 \
            -f docker/vllm/Dockerfile.rayserve .
          docker push "${REPO}":"${TAG}"
          docker rmi "${REPO}":"${TAG}"
          yes | docker system prune

  example-on-g6xl-runner-1:
    needs: [example-on-build-runner]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
      - run: |
          nvidia-smi
  
  example-on-g6xl-runner-2:
    needs: [example-on-build-runner]
    runs-on:
      - codebuild-runner-${{ github.run_id }}-${{ github.run_attempt }}
        fleet:x86-g6xl-runner
    steps:
      - uses: actions/checkout@v5
      - run: .github/scripts/runner_setup.sh
      - run: |
          nvidia-smi
